# Importing the libraries

In [2]:
#Libraries to be imported
from sklearn.decomposition import PCA
from sklearn.ensemble import AdaBoostClassifier,RandomForestClassifier
from sklearn.model_selection import train_test_split,StratifiedKFold
from sklearn.metrics import f1_score,precision_score,recall_score,accuracy_score, confusion_matrix,classification_report
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression 
from sklearn.model_selection import GridSearchCV 
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest,chi2,f_classif,mutual_info_classif
from sklearn.model_selection import StratifiedKFold, train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler,MinMaxScaler,RobustScaler,OneHotEncoder,Normalizer
from sklearn.naive_bayes import GaussianNB

# Getting Data

In [6]:

import pandas as pd
import numpy as np
data=pd.read_csv("C:/Users/AnmitY/OneDrive/Desktop/training_data.csv")
target=pd.read_csv("C:/Users/AnmitY/OneDrive/Desktop/training_data_targets.csv",names=['y'])


# Preprocessing the data

## taking care of empty values

In [7]:

median=data.median()
data=data.fillna(median)
data

age  gendera        BMI  hypertensive  atrialfibrillation  \
0      83        2  21.551321             0                   0   
1      72        2  53.018931             1                   1   
2      74        2  28.187883             1                   1   
3      44        1  28.486719             0                   0   
4      89        1  28.187883             1                   1   
...   ...      ...        ...           ...                 ...   
1053   68        1  33.669081             1                   1   
1054   85        1  24.040864             1                   1   
1055   63        2  13.673625             1                   1   
1056   89        1  25.312500             0                   0   
1057   58        1  56.132848             1                   1   

      CHD with no MI  diabetes  deficiencyanemias  depression  Hyperlipemia  \
0                  0         0                  0           0             0   
1                  0         0                  0           0             1   
2                  0         0                  0           0             0   
3                  0         0                  0           0             0   
4                  0         1                  0           0             1   
...              ...       ...                ...         ...           ...   
1053               0         1                  0           0             0   
1054               0         0                  0           0             0   
1055               0         0                  0           1             1   
1056               1         1                  1           0             1   
1057               0         1                  1           0             1   

      ...  Blood sodium  Blood calcium    Chloride  Anion gap  Magnesium ion  \
0     ...    133.230769       8.712500   95.846154  14.615385       1.841667   
1     ...    132.600000       7.475000  104.800000  11.800000       2.160000   
2     ...    138.666667       8.257143  104.833333  14.166667       2.085714   
3     ...    139.250000       8.714286   97.333333  14.583333       2.225000   
4     ...    141.533333       8.390909  109.066667  20.800000       2.446154   
...   ...           ...            ...         ...        ...            ...   
1053  ...    135.666667       7.857143   97.400000  11.266667       2.328571   
1054  ...    144.142857       9.371429  107.571429  10.142857       2.157143   
1055  ...    139.125000       9.337500  100.125000  12.000000       1.862500   
1056  ...    139.000000       9.655556   99.916667  15.500000       2.133333   
1057  ...    139.666667       8.777778   95.416667  11.916667       2.170000   

            PH  Bicarbonate  Lactic acid       PCO2  EF  
0     7.310000    27.000000        1.600  50.000000  50  
1     7.383333    20.000000        1.200  32.000000  55  
2     7.400000    23.500000        1.775  37.625000  75  
3     7.380000    31.416667        1.600  43.416667  30  
4     7.328889    16.266667        1.800  28.625000  25  
...        ...          ...          ...        ...  ..  
1053  7.441250    31.066667        1.500  47.000000  25  
1054  7.390000    30.285714        2.000  57.428571  55  
1055  7.320000    31.500000        1.200  67.500000  50  
1056  7.380000    28.416667        1.700  43.416667  50  
1057  7.365000    37.000000        1.025  70.666667  55  

[1058 rows x 48 columns]

## encoding the data

In [8]:
gender=np.array(data.gendera).reshape(-1,1)

In [9]:

#One hot encoder
ohd=OneHotEncoder()
gender=ohd.fit_transform(gender).toarray().astype(int)
gender=pd.DataFrame(gender)
add=ohd.fit_transform(data.iloc[:,3:12]).toarray().astype(int)
data.drop(columns=data.columns[3:12],inplace=True)
add=pd.DataFrame(add)



In [10]:
gender

0  1
0     0  1
1     0  1
2     0  1
3     1  0
4     1  0
...  .. ..
1053  1  0
1054  1  0
1055  0  1
1056  1  0
1057  1  0

[1058 rows x 2 columns]

In [11]:
data.drop(columns=data.columns[1],inplace=True)
data

age        BMI  heart rate  Systolic blood pressure  \
0      83  21.551321   66.320000               111.160000   
1      72  53.018931  119.515152               101.620690   
2      74  28.187883   65.727273               115.705882   
3      44  28.486719   98.269231               136.880000   
4      89  28.187883   90.666667                99.275862   
...   ...        ...         ...                      ...   
1053   68  33.669081   85.718750               120.548387   
1054   85  24.040864   66.758621               112.515152   
1055   63  13.673625  108.807692               137.695652   
1056   89  25.312500   70.217391               110.956522   
1057   58  56.132848   87.960000               148.250000   

      Diastolic blood pressure  Respiratory rate  temperature      SP O2  \
0                    50.440000         18.440000    35.796296  95.000000   
1                    53.862069         23.272727    36.111111  92.606061   
2                    55.970588         16.307692    37.317460  98.971429   
3                    84.720000         22.307692    36.819444  97.925926   
4                    52.379310         23.666667    36.571429  94.166667   
...                        ...               ...          ...        ...   
1053                 56.548387         19.189189    37.574074  95.156250   
1054                 59.878788         25.714286    37.180555  96.482759   
1055                 77.000000         20.730769    36.730159  95.791667   
1056                 50.608696         24.565217    36.518519  95.826087   
1057                 65.750000         20.880000    36.577778  89.720000   

      Urine output  hematocrit  ...  Blood sodium  Blood calcium    Chloride  \
0           1845.0   31.587500  ...    133.230769       8.712500   95.846154   
1            790.0   25.600000  ...    132.600000       7.475000  104.800000   
2           3245.0   30.100000  ...    138.666667       8.257143  104.833333   
3           6056.0   40.887500  ...    139.250000       8.714286   97.333333   
4            814.0   33.668421  ...    141.533333       8.390909  109.066667   
...            ...         ...  ...           ...            ...         ...   
1053        2140.0   28.420000  ...    135.666667       7.857143   97.400000   
1054         937.0   35.500000  ...    144.142857       9.371429  107.571429   
1055         715.0   31.857143  ...    139.125000       9.337500  100.125000   
1056        3855.0   30.010000  ...    139.000000       9.655556   99.916667   
1057        6875.0   27.187500  ...    139.666667       8.777778   95.416667   

      Anion gap  Magnesium ion        PH  Bicarbonate  Lactic acid       PCO2  \
0     14.615385       1.841667  7.310000    27.000000        1.600  50.000000   
1     11.800000       2.160000  7.383333    20.000000        1.200  32.000000   
2     14.166667       2.085714  7.400000    23.500000        1.775  37.625000   
3     14.583333       2.225000  7.380000    31.416667        1.600  43.416667   
4     20.800000       2.446154  7.328889    16.266667        1.800  28.625000   
...         ...            ...       ...          ...          ...        ...   
1053  11.266667       2.328571  7.441250    31.066667        1.500  47.000000   
1054  10.142857       2.157143  7.390000    30.285714        2.000  57.428571   
1055  12.000000       1.862500  7.320000    31.500000        1.200  67.500000   
1056  15.500000       2.133333  7.380000    28.416667        1.700  43.416667   
1057  11.916667       2.170000  7.365000    37.000000        1.025  70.666667   

      EF  
0     50  
1     55  
2     75  
3     30  
4     25  
...   ..  
1053  25  
1054  55  
1055  50  
1056  50  
1057  55  

[1058 rows x 38 columns]

# Feature Selection

In [12]:
data=SelectKBest(mutual_info_classif,k=34).fit_transform(data,target)

C:\Users\AnmitY\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


## Normalize the data

In [13]:

n=Normalizer(norm='l2',copy=True)
data=n.fit_transform(data)

In [14]:
n=Normalizer(norm='l2',copy=True)
data=n.fit_transform(data)

In [15]:
data=pd.DataFrame(data)

In [16]:
data1=pd.concat([data,add,gender],axis=1)
data1

0         1         2         3         4         5         6   \
0     0.006399  0.001662  0.005113  0.001422  0.002760  0.007324  0.142241   
1     0.006994  0.005150  0.011609  0.002261  0.003508  0.008995  0.076736   
2     0.008200  0.003123  0.007283  0.001807  0.004135  0.010967  0.359569   
3     0.005055  0.003273  0.011289  0.002563  0.004230  0.011250  0.695728   
4     0.002258  0.000715  0.002300  0.000600  0.000928  0.002389  0.020648   
...        ...       ...       ...       ...       ...       ...       ...   
1053  0.006750  0.003342  0.008509  0.001905  0.003730  0.009446  0.212428   
1054  0.041704  0.011795  0.032754  0.012616  0.018242  0.047338  0.459727   
1055  0.018937  0.004110  0.032707  0.006231  0.011041  0.028794  0.214922   
1056  0.016691  0.004747  0.013169  0.004607  0.006849  0.017972  0.722985   
1057  0.008253  0.007987  0.012516  0.002971  0.005205  0.012767  0.978286   

            7         8         9   ...  10  11  12  13  14  15  16  17  0   \
0     0.000286  0.002244  0.002641  ...   1   0   1   0   1   0   1   0   0   
1     0.000283  0.002961  0.003371  ...   1   0   0   1   1   0   1   0   0   
2     0.000398  0.003267  0.003914  ...   1   0   1   0   0   1   1   0   0   
3     0.000522  0.003521  0.003912  ...   1   0   1   0   1   0   1   0   1   
4     0.000100  0.000745  0.000873  ...   1   0   0   1   0   1   1   0   1   
...        ...       ...       ...  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..   
1053  0.000320  0.002847  0.003205  ...   1   0   1   0   0   1   1   0   1   
1054  0.001818  0.015831  0.016526  ...   1   0   1   0   1   0   1   0   1   
1055  0.001125  0.007966  0.009357  ...   0   1   0   1   1   0   1   0   0   
1056  0.000642  0.005870  0.006695  ...   1   0   0   1   0   1   1   0   1   
1057  0.000448  0.003863  0.004475  ...   1   0   0   1   1   0   1   0   1   

      1   
0      1  
1      1  
2      1  
3      0  
4      0  
...   ..  
1053   0  
1054   0  
1055   1  
1056   0  
1057   0  

[1058 rows x 54 columns]

# PCA

In [114]:
pca=PCA(n_components=29)
data1=pca.fit_transform(data1)

# Training


In [17]:

data1=np.array(data1)
target=np.array(target)
skf=StratifiedKFold(n_splits=4)
for train, test in skf.split(data1,target):
        x_train = data1[train]
        y_train = target[train]
        x_test = data1[test]
        y_test = target[test]

In [18]:
y_train=np.array(y_train)
y_train=y_train.reshape(-1)


In [117]:
x_train=pd.DataFrame(x_train)
x_train

0         1         2         3         4         5         6   \
0   -1.484181  0.412416 -0.042278 -0.012640 -0.182451 -0.125988  0.714445   
1   -0.131137 -0.587478 -1.382873 -0.654713  0.483496  0.042782  0.052679   
2   -0.033219 -0.492186 -0.909935  0.713261 -0.093792 -1.114636  0.134254   
3   -1.291295 -0.302458  1.124959 -0.107480  0.021719  0.127314  0.387815   
4    1.597109 -1.093034 -0.029886 -0.113020 -0.243532  0.006099  0.354383   
..        ...       ...       ...       ...       ...       ...       ...   
789 -1.099092 -1.259183  0.278739  0.492779 -0.077302  0.479418  0.229886   
790 -0.603504 -1.211829  0.127000 -0.047012  0.025362 -0.175235 -0.813431   
791  0.161501 -0.244380 -0.516538  1.026196 -1.299025  0.029805  1.019706   
792 -0.726912  1.166895 -0.091815  0.092092  0.467750 -0.169054 -0.904962   
793 -0.968833  0.437248 -0.241502 -0.503513 -0.057395 -0.804524 -0.288880   

           7         8         9   ...        19        20        21  \
0   -0.352626  0.091572 -0.235171  ... -0.001702  0.000788  0.000583   
1   -0.201005 -0.018393 -0.182303  ...  0.001024 -0.000968 -0.000376   
2   -0.027431 -0.088559  0.143445  ... -0.000714 -0.002311 -0.002232   
3   -0.187912 -0.109723 -0.111187  ...  0.001049 -0.000566  0.001211   
4   -0.142787 -0.105472 -0.172691  ... -0.000380  0.000019 -0.000204   
..        ...       ...       ...  ...       ...       ...       ...   
789 -0.131906 -0.065462 -0.218912  ... -0.000648 -0.002712  0.000202   
790  0.121985 -0.225534  0.052186  ... -0.004262  0.003111 -0.000842   
791 -0.266948 -0.003868  0.129287  ... -0.001444  0.000351  0.000323   
792 -0.145815 -0.189476  0.194574  ...  0.001313 -0.007998 -0.001096   
793 -0.133741 -0.004077 -0.112109  ... -0.001440  0.004225  0.000008   

           22        23        24            25        26        27        28  
0   -0.000020 -0.000031  0.000145 -1.941259e-04 -0.000001 -0.000389 -0.000196  
1    0.001830 -0.001016 -0.000974  9.150545e-07 -0.000775  0.000034  0.000087  
2   -0.000565  0.000729 -0.000358 -3.372529e-04 -0.000269  0.000051 -0.000093  
3   -0.001014 -0.000636  0.000251  6.317796e-04  0.000211 -0.000302 -0.000283  
4    0.000014 -0.000323  0.000144 -7.247909e-05 -0.000045  0.000123  0.000063  
..        ...       ...       ...           ...       ...       ...       ...  
789  0.000992 -0.001156 -0.000744  1.664650e-03  0.001149  0.001522 -0.000061  
790  0.000591 -0.000541  0.001347  6.572988e-04 -0.000647 -0.003141  0.000526  
791 -0.000103  0.000099  0.000195 -1.793497e-04  0.000092  0.000267  0.000040  
792  0.004782 -0.001684 -0.000233 -8.647030e-04 -0.001201  0.000429  0.000628  
793 -0.002339  0.000447  0.000687 -8.107092e-04  0.001815  0.000882 -0.000815  

[794 rows x 29 columns]

## Getting Parameters for GridSearchCV

In [128]:
#Looking for Parameters

param_grid2={'n_neighbors':[5,6,7,10,12,15,16,17,18,20,23,24,34,56],'weights':['uniform', 'distance'],'algorithm':['auto', 'ball_tree', 'kd_tree', 'brute'],'leaf_size':[5,6,7,8,9,10,11],'p':[1,2,3]}#knn
param_grid3={'kernel':['sigmoid','liner','poly', 'rbf'],'C':[0.1,1,5,10,15,20,30,40,100],'gamma':['scale', 'auto'],'coef0':[0,1,2,3],'shrinking':[True,False],'decision_function_shape':['ovo','ovr']}#SVC
param_grid4={'activation':['identity', 'logistic', 'tanh', 'relu'],'solver':[ 'sgd', 'adam'],'max_iter':[200,400,800,1000],'alpha':[0.0001,0.0005,0.001,0.005,0.01]}#MLP classifier
param_grid5={'penalty':['l1', 'l2', 'elasticnet', 'None'],'solver':['lbfgs' 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'],'max_iter':[100,200,400,800,1000,2000,1500],'C':[0.1,0.001,0.0001,0.005,2],'class_weight':['dict','balanced']}#logarithmicRegression

param_grid7={'n_estimators':[10,15,16,20,100,200],'criterion':['gini', 'entropy','log_loss'],'max_features':['sqrt', 'log2', 'None'],'ccp_alpha':[0.02,0.01,0.05,0.1],'max_depth':[10,20,30,50,100,200]}#RandomForestClassifier
param_grid8={'var_smoothing':[1e-10,1e-9,1e-8,1e-7,1e-6]}#GaussianNB

In [119]:
gv2=GridSearchCV(estimator=KNeighborsClassifier(),param_grid=param_grid2,cv=6,n_jobs=-1,scoring='f1_macro')
gv2.fit(x_train,y_train)
gv2.best_params_

C:\Users\AnmitY\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:976: UserWarning: One or more of the test scores are non-finite: [       nan 0.55560314        nan ... 0.53606112        nan 0.54391844]
  warnings.warn(


{'algorithm': 'auto',
 'leaf_size': 5,
 'n_neighbors': 5,
 'p': 3,
 'weights': 'distance'}

In [120]:
gv3=GridSearchCV(estimator=SVC(),param_grid=param_grid3,cv=6,n_jobs=-1,scoring='f1_macro')
gv3.fit(x_train,y_train)
gv3.best_params_

C:\Users\AnmitY\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
1728 fits failed out of a total of 6912.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
266 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\AnmitY\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\AnmitY\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\AnmitY\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\AnmitY\anaconda3\Lib\site

{'C': 40,
 'coef0': 0,
 'decision_function_shape': 'ovo',
 'gamma': 'scale',
 'kernel': 'sigmoid',
 'shrinking': True}

In [121]:
gv4=GridSearchCV(estimator=MLPClassifier(),param_grid=param_grid4,cv=6,n_jobs=-1,scoring='f1_macro')
gv4.fit(x_train,y_train)
gv4.best_params_

C:\Users\AnmitY\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


{'activation': 'relu', 'alpha': 0.0005, 'max_iter': 1000, 'solver': 'adam'}

In [122]:
gv5=GridSearchCV(estimator=LogisticRegression(),param_grid=param_grid5,cv=6,n_jobs=-1,scoring='f1_macro')
gv5.fit(x_train,y_train)
gv5.best_params_

C:\Users\AnmitY\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
7350 fits failed out of a total of 8400.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
4200 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\AnmitY\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\AnmitY\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\AnmitY\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\AnmitY\anaconda3\Lib\sit

{'C': 2,
 'class_weight': 'balanced',
 'max_iter': 100,
 'penalty': 'l2',
 'solver': 'newton-cg'}

C:\Users\AnmitY\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


{'algorithm': 'SAMME'}

In [129]:
gv7=GridSearchCV(estimator=RandomForestClassifier(),param_grid=param_grid7,cv=6,n_jobs=-1,scoring='f1_macro')
gv7.fit(x_train,y_train)
gv7.best_params_


C:\Users\AnmitY\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
2592 fits failed out of a total of 7776.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
2054 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\AnmitY\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\AnmitY\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\AnmitY\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\AnmitY\anaconda3\Lib\sit

{'ccp_alpha': 0.01,
 'criterion': 'entropy',
 'max_depth': 10,
 'max_features': 'sqrt',
 'n_estimators': 10}

In [130]:
gv8=GridSearchCV(estimator=GaussianNB(),param_grid=param_grid8,cv=6,n_jobs=-1,scoring='f1_macro')
gv8.fit(x_train,y_train)
gv8.best_params_

{'var_smoothing': 1e-07}

In [132]:
gnb=GaussianNB(var_smoothing=1e-07)
svc=SVC(C=40,coef0=0,decision_function_shape='ovo',gamma='scale',kernel='sigmoid',shrinking= True)#updated
knn=KNeighborsClassifier(algorithm='auto',leaf_size=5,n_neighbors= 5,p= 3,weights= 'distance')#updated
mlp=MLPClassifier(activation= 'relu',alpha=0.0005, max_iter= 1000, solver= 'adam')
lr=LogisticRegression(C= 2,class_weight= 'balanced',max_iter= 100,penalty= 'l2',solver='newton-cg')
rfc=RandomForestClassifier(ccp_alpha= 0.01,criterion= 'entropy',max_depth= 10,max_features= 'sqrt',n_estimators= 10)#updated

## Fitting the training 

In [133]:
lr.fit(x_train,y_train)
svc.fit(x_train,y_train)
rfc.fit(x_train,y_train)
knn.fit(x_train,y_train)
mlp.fit(x_train,y_train)
gnb.fit(x_train,y_train)

C:\Users\AnmitY\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


GaussianNB(var_smoothing=1e-07)

## Predicting on x_test

In [134]:
y_predict1=lr.predict(x_test)
y_predict2=svc.predict(x_test)
y_predict4=rfc.predict(x_test)
y_predict5=knn.predict(x_test)
y_predict6=mlp.predict(x_test)
y_predict7=gnb.predict(x_test)

# Checking accuracy

In [135]:
print('Logistic Regression')

print(confusion_matrix(y_predict1,y_test))
print(accuracy_score(y_predict1,y_test))
print(classification_report(y_predict1,y_test))

Logistic Regression
0.5640263449320977
0.6498538011695907
0.5773438973778533
[[157  14]
 [ 71  22]]
0.678030303030303
              precision    recall  f1-score   support

           0       0.69      0.92      0.79       171
           1       0.61      0.24      0.34        93

    accuracy                           0.68       264
   macro avg       0.65      0.58      0.56       264
weighted avg       0.66      0.68      0.63       264



In [136]:
print("Support Vector Machine for Classification")

print(confusion_matrix(y_predict2,y_test))
print(accuracy_score(y_predict2,y_test))
print(classification_report(y_predict2,y_test))

Support Vector Machine for Classification
0.463841059602649
0.46271929824561403
0.4651282051282052
[[192  33]
 [ 36   3]]
0.7386363636363636
              precision    recall  f1-score   support

           0       0.84      0.85      0.85       225
           1       0.08      0.08      0.08        39

    accuracy                           0.74       264
   macro avg       0.46      0.47      0.46       264
weighted avg       0.73      0.74      0.73       264



Adaboost without any classifier chosen
0.5838268501555111
0.5679824561403509
0.671008274593932
[[221  30]
 [  7   6]]
0.8598484848484849
              precision    recall  f1-score   support

           0       0.97      0.88      0.92       251
           1       0.17      0.46      0.24        13

    accuracy                           0.86       264
   macro avg       0.57      0.67      0.58       264
weighted avg       0.93      0.86      0.89       264



In [138]:
print('Random Forest Classifier')

print(confusion_matrix(y_predict4,y_test))
print(accuracy_score(y_predict4,y_test))
print(classification_report(y_predict4,y_test))

Random Forest Classifier
0.5107928081334202
0.5211988304093567
0.6343629343629344
[[225  34]
 [  3   2]]
0.8598484848484849
              precision    recall  f1-score   support

           0       0.99      0.87      0.92       259
           1       0.06      0.40      0.10         5

    accuracy                           0.86       264
   macro avg       0.52      0.63      0.51       264
weighted avg       0.97      0.86      0.91       264



In [139]:
print('KNN')

print(confusion_matrix(y_predict5,y_test))
print(accuracy_score(y_predict5,y_test))
print(classification_report(y_predict5,y_test))

KNN
0.5006053268765133
0.5043859649122807
0.5073770491803279
[[211  33]
 [ 17   3]]
0.8106060606060606
              precision    recall  f1-score   support

           0       0.93      0.86      0.89       244
           1       0.08      0.15      0.11        20

    accuracy                           0.81       264
   macro avg       0.50      0.51      0.50       264
weighted avg       0.86      0.81      0.83       264



In [140]:
print('MLP')

print(confusion_matrix(y_predict6,y_test))
print(accuracy_score(y_predict6,y_test))
print(classification_report(y_predict6,y_test))

MLP
0.5351430667644901
0.5321637426900585
0.5495867768595041
[[211  31]
 [ 17   5]]
0.8181818181818182
              precision    recall  f1-score   support

           0       0.93      0.87      0.90       242
           1       0.14      0.23      0.17        22

    accuracy                           0.82       264
   macro avg       0.53      0.55      0.54       264
weighted avg       0.86      0.82      0.84       264



In [141]:
print('Gaussian NB')

print(confusion_matrix(y_predict7,y_test))
print(accuracy_score(y_predict7,y_test))
print(classification_report(y_predict7,y_test))

Gaussian NB
0.5839323467230444
0.570906432748538
0.6250268528464017
[[216  29]
 [ 12   7]]
0.8446969696969697
              precision    recall  f1-score   support

           0       0.95      0.88      0.91       245
           1       0.19      0.37      0.25        19

    accuracy                           0.84       264
   macro avg       0.57      0.63      0.58       264
weighted avg       0.89      0.84      0.87       264



# Applying adaboost on randomforest classifier

In [3]:
adb2=AdaBoostClassifier(LogisticRegression(C= 2,class_weight= 'balanced',max_iter= 100,penalty= 'l2',solver='newton-cg'),algorithm= 'SAMME')

In [4]:
adb2.fit(x_train,y_train)
y_predict8=adb2.predict(x_test)

print(confusion_matrix(y_predict8,y_test))
print(accuracy_score(y_predict8,y_test))
print(classification_report(y_predict8,y_test))

NameError: name 'x_train' is not defined